import { writeFileSync, readFileSync, readdirSync } from "node:fs";
import yaml from "js-yaml";
import { isBlacklisted } from "../src/blacklist.js";
const REPO=process.env.HOME+"/Developer/korean-art-lexicon/";
const DIR=REPO+"data/persons/";
const APPLY=process.argv.includes("--apply");
// 롱테일 패스3 (2기관 MMCA+SeMA 웹 검증). [en, url, note]. 전부 pending_review.
const M={
"양민하":["Yang Minha","https://yangminha.com/","본인사이트. high"],
"신석필":["Shin Suk Pil","https://www.artsy.net/artist/shin-suk-pil","Artsy(슬러그). 약-medium"],
"박승훈":["Park Seung Hoon","https://www.photobrusselsfestival.com/park-seung-hoon","PhotoBrussels(사진). high"],
"유희영":["Yoo Hee-young","https://www.koreatimes.co.kr/lifestyle/arts-theater/20181022/yoo-hee-youngs-abstract-paintings-reflect-his-struggle-with-colors","코리아타임스(전 SeMA관장). high"],
"앤디워홀":["Andy Warhol","https://www.e-flux.com/announcements/449204/to-the-world-through-art","e-flux MMCA소장(미국). high"],
"강민수":["MinSoo Kang","https://www.joongjunggallery.com/","중정갤러리(도예). high"],
"정기호":["Jung Ki Ho","https://www.artsy.net/artist/jung-ki-ho/about","Artsy(슬러그). 약-medium"],
"강병인":["Kang Byung-in","https://www.koreaherald.com/article/10691906","코리아헤럴드(캘리그래피). high"],
"천제런":["Chen Chieh-jen","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=201802070001007","MMCA英(대만). high"],
"위안광밍":["Yuan Goang-Ming","https://about.asianart.org/press/acclaimed-taiwanese-artist-yuan-goang-ming-brings-venice-biennale-triumph-to-asian-art-museum-in-first-north-american-solo-exhibition/","아시아미술관SF(대만). high"],
"국형걸":["Hyoung-gul Kook","https://www.architectmagazine.com/firms/hg-architecture","Architect Mag(건축/설치). high"],
"임영선":["Young Sun Lim","https://www.commoncrowbooks.com/pages/books/0063045/young-jin-kim-hwa-young-park-bien-u-bae-young-sun-lim/inside-out-four-artists-from-korea","국립현대 1997 도록. medium"],
"김기영":["Kim Ki Young","https://chapterii.org/artists/74-kim-ki-young/","Chapter II(조각). medium"],
"서고운":["Goun Seo","https://sema.seoul.go.kr/kr/support/emerging_artist/detail_info?actNo=245","SeMA 신진(영문 Artsy). medium"],
"김하영":["Kim HaYoung","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhFlag=3&exhId=201412240000193","MMCA英 YKA2014. high"],
"강영민":["Youngmin Kang","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=201501300000200","MMCA英. high"],
"신제현":["Shin Jehyun","https://hobancf.or.kr/exhibition/artist_view.php?seq=252","호반문화재단(MMCA英은 SHIN Jae Hyun). medium"],
"폴 카잔더":["Paul Kajander","https://artsonje.org/en/exhibition/art-sonje-banner-project-1-paul-kajander-what-cannot-be-is-what/","아트선재(캐나다). medium"],
"김태호":["Kim Tae-Ho","https://www.pearllam.com/artist/kim-tae-ho/","Pearl Lam(MMCA+SeMA소장, 단색화 b.1948). medium"],
"안세권":["Ahn Sekwon","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=201412110000192","MMCA英(사진). high"],
"이배경":["Lee Bei-Kyoung","https://www.mmca.go.kr/artStudio/artistDetail.do?cinArtId=201311100000452","MMCA 창동레지던시(조각). high"],
"최선":["Choi Sun","http://chapterii.org/artists/75-choi-sun/","Chapter II(MMCA창동+SeMA난지). medium"],
"고이즈미 메이로":["Meiro Koizumi","https://www.mujin-to.com/en/artist/koizumi/","Mujin-to(일본). high"],
"오유경":["Oh Youkyeong","https://www.ngalleryart.com/youkyeongoh","N Gallery(조각/설치). medium"],
"연기백":["Youn Kibaik","https://amadoart.org/exhibition/","Amado Art Space(YOUN Kibaik). medium"],
"유영운":["Yoo Young-wun","https://www.instagram.com/yoo_young_wun/","본인IG(SeMA전, ≠유영국). medium"],
"루크 슈뢰더":["Luuk Schröder","https://www.mondriaanfonds.nl/en/apply-for-a-grant/grants/residency-2124/mmca-residency-changdong-seoul-south-korea/","Mondriaan Fund MMCA창동(네덜란드). high"],
"서정화":["Jeonghwa Seo","https://jeonghwaseo.com/cv","본인(MMCA+SeMA). high"],
"이정화":["Lee Jung Hwa","https://www.osjartfactory.com/leejunghwa","OSJ갤러리. medium"],
"안창모":["Changmo Ahn","https://www.archilovers.com/projects/128773/crow-s-eye-view-the-korean-peninsula.html","베니스2014(건축사학). high"],
"정문경":["Chung Munkyung","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=835199","SeMA英 난지. high"],
"서정희":["Seo Jung Hee Biann","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=406","SeMA英('Biann' 본인명). high"],
"노상호":["Noh Sangho","https://www.arariogallery.com/artists/227-noh-sangho/","아라리오(MMCA아트뱅크). high"],
"홍원석":["Hong WonSeok","https://ocula.com/artists/hong-wonseok/","Ocula+아라리오. high"],
"박성원":["Sung-Won Park","https://www.artsy.net/artist/sung-won-park","Artsy. 약-medium"],
"김근배":["Geun Bae Kim","https://www.artsper.com/us/contemporary-artists/south-korea/85692/geun-bae-kim","Artsper(MMCA Research). 약-medium"],
"허수영":["Heo Suyoung","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=472","SeMA英 난지. high"],
"선우훈":["Sunwoo Hoon","https://www.hkw.de/en/programme/global-fascisms/sunwoo-hoon","HKW베를린+4A시드니. high"],
"유걸":["Yoo Kerl","https://www.e-flux.com/announcements/299522/contemporary-korean-architecture-cosmopolitan-look-1989-2019","e-flux MMCA건축(본인표기). high"],
"김종규":["Kim Jong Kyu","https://www.e-flux.com/announcements/299522/contemporary-korean-architecture-cosmopolitan-look-1989-2019","e-flux MMCA건축. high"],
"조민석":["Minsuk Cho","https://www.e-flux.com/announcements/299522/contemporary-korean-architecture-cosmopolitan-look-1989-2019","e-flux/SeMA 'Cho Minsuk'(건축 Mass Studies). high"],
"최문규":["Moongyu Choi","https://www.e-flux.com/announcements/299522/contemporary-korean-architecture-cosmopolitan-look-1989-2019","e-flux MMCA건축. high"],
"존 아캄프라":["John Akomfrah","https://www.tate.org.uk/art/artists/sir-john-akomfrah-cbe-9259","Tate(영국/가나). high"],
"최대진":["Daejin Choi","https://www.artsy.net/artist/daejin-choi","Artsy(SeMA난지). 약-medium"],
"양 푸동":["Yang Fudong","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=201703080000527","MMCA英소장(중국). high"],
"짐다인":["Jim Dine","https://sema.seoul.go.kr/en/knowledge_research/collection/landing","SeMA소장(미국). high"],
"크리스토":["Christo","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=202202170001495","MMCA英소장(미/불). high"],
"잭슨홍":["Jackson Hong","http://chapterii.org/press/237-jackson-hong-what-things-dream-about-at-mmca-seoul/","Chapter II(MMCA전). high"],
"오경화":["Oh Kyung Hwa","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhFlag=2&exhId=202403220001771","MMCA英(≠오경환 남). high"],
"바이런 킴":["Byron Kim","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=202001150001262","MMCA英+SeMA남서울. high"],
"히와 케이":["Hiwa K","https://mediacityseoul.kr/en/yesterday/participants/hiwa-k","서울미디어시티(SeMA, 이라크/독일). high"],
"이귀영":["Lee Gui-Young","https://www.mmca.go.kr/upload/artInfo/2016/04/2016041802174050217703.pdf","MMCA 창동레지던시. high"],
"리슨투더시티":["Listen to the City","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=503089","SeMA英(콜렉티브). high"],
"A.R. 펭크":["A.R. Penck","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=202202170001495","MMCA英소장(독일). high"],
"목진요":["Jin-Yo Mok","https://whitney.org/artists/9665","Whitney. high"],
"후니다킴":["Hoonida Kim","https://hoonida.com/about/","본인(MMCA전). high"],
"류한길":["Ryu Hankil","https://www.mmca.go.kr/engN/pop/exhibition/2012/09/13/detail1_eng.html","MMCA英(사운드). high"],
"심승욱":["Sim Seung-Wook","https://www.instagram.com/simseungwook/","본인IG(국제 Seung Wook Sim). medium"],
"하딤 알리":["Khadim Ali","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=201707260000613","MMCA英(아프간/호주). high"],
"김용관":["Kim Yong-gwan","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=202001090001222","MMCA英+SeMA. high"],
"푸하하하프렌즈":["FHHH Friends","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=202303310001637","MMCA英(건축콜렉티브). high"],
"이동근":["Donggeun Lee","https://pageroom8.com/exhibition/?bmode=view&idx=94903342","PageRoom8+두산. medium"],
"전몽각":["Jeon Mong Gag","https://museumhanmi.or.kr/en/post_1178/","뮤지엄한미(사진). high"],
"이경모":["Lee Kyung-mo","https://view.asiae.co.kr/en/article/2022122322514133896","아시아경제英(사진). medium"],
"최윤석":["Choi Yoonsuk","https://sema.seoul.go.kr/en/support/nanji_residency/detail_info?actNo=1461626","SeMA英 난지. high"],
"유화수":["Hwasoo Yoo","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=1314927","SeMA英. high"],
"박현정":["Hyunjung Park","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=480970","SeMA英. high"],
"이예승":["YeSeung Lee","https://yeseunglee.net","본인(MMCA창동+SeMA난지). medium"],
"쉬린 네샤트":["Shirin Neshat","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=201403310000072","MMCA英 회고전(이란). high"],
"여동헌":["Donghun Yeo","http://www.iartpark.com/artists/37-donghun-yeo/","가나아트파크. medium"],
"신이피":["Ifie Sin","https://sinifie.wixsite.com/artist/1","본인CV(MMCA2018+SeMA2020). high"],
"배헤윰":["Bä Hejum","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=202101210001365","MMCA英 YKA2021(국제 Hejum Bä). high"],
"하야시 야스오":["Hayashi Yasuo","https://www.momat.go.jp/craft-museum/en/artists/aha048","일본 국립공예관(일본). high"],
"김정숙":["Kim Chungsook","https://www.mmca.go.kr/collections/collectionsDetailPage.do?wrkinfoSeqno=4742","MMCA소장(조각 b.1917). high"],
"김소영":["Kim So-young","https://www.mmca.go.kr/pr/newsDetail.do?bdCId=201805310006323","MMCA 고양레지던시(≠영화학자). high"],
"황동욱":["Hwang Dongwook","https://www.e-flux.com/announcements/532913/young-korean-artists-2023annotating-the-museum/","e-flux MMCA YKA2023. high"],
"유리 패티슨":["Yuri Pattison","https://www.e-flux.com/announcements/470228/watch-and-chill-2-0-streaming-senses","e-flux MMCA(아일랜드)+SeMA미디어시티. high"],
"씨씨 우":["Cici Wu","https://36.bienal.org.br/en/artista/cici-wu/","상파울루비엔날레+SeMA미디어시티. high"],
"곽이브":["Eve Kwak","https://www.instagram.com/p/DTI9_ZqknDm/","IG(MMCA고양레지). medium"],
"송민정":["Song Min Jung","https://www.e-flux.com/announcements/269644/young-korean-artists-2019-liquid-glass-sea/","e-flux MMCA YKA2019. high"],
"김방주":["Kim Bangjoo","https://www.e-flux.com/announcements/6785593/sak-da-the-poetics-of-decomposition","e-flux MMCA2026. high"],
"고재욱":["Jaewook Koh","https://www.jaewookkoh.com/cv","본인CV(MMCA+SeMA). high"],
"범진용":["Jinyong Beom","https://www.galleryartpresso.com/product-page/beom-jin-yong","갤러리Artpresso(SeMA난지). medium"],
"최하늘":["Choi Haneyl","https://www.e-flux.com/announcements/269644/young-korean-artists-2019-liquid-glass-sea/","e-flux MMCA(SeMA는 Haneul). high"],
"이창원":["Changwon Lee","https://www.mori.art.museum/english/contents/mamproject/project017/index.html","모리미술관(SeMA소장). medium"],
"장진승":["Jinseung Jang","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=1065367","SeMA英. high"],
"이재욱":["Jaewook Lee","http://www.jaewooklee.com/about","본인CV(SeMA2016, ≠배우). medium"],
"김동희":["Donghee Kim","https://sema.seoul.go.kr/semazine/2020/en/exhibitions/this-event.html","SeMA英(MMCA INTRO2015). high"],
"임창민":["Lim Chang Min","https://aaa.org.hk/en/collections/search/library/sea-of-light-park-jin-won-lee-eun-joo-lee-lee-nam-lim-chang-min-cracker","Asia Art Archive(영상). medium"],
"서해영":["Haeyoung Seo","https://www.zku-berlin.org/people/haeyoung-seo/","ZK/U베를린(SeMA). medium"],
"김을지로":["Kim Uljiro","https://uljiro.land/","본인(MMCA YKA2025). high"],
"권아람":["Kwon Ahram","https://www.gallerykiche.com/artists/1483","갤러리키체(SeMA난지+MMCA고양). high"],
"켄트 찬":["Kent Chan","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=1199291","SeMA英 미디어시티(싱가포르). high"],
"권동현×권세정":["Gwon Donghyun × Kwon Seajung","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhFlag=2&exhId=202503040001913","MMCA英(듀오). high"],
"전지인":["Juen Jiin","https://www.mmca.go.kr/artStudio/artistDetail.do?cinArtId=202501200000434","MMCA 창동레지(공식 Juen Jiin). high"],
"리아 리잘디":["Riar Rizaldi","http://geumcheon.blogspot.com/2018/02/riar-rizaldi.html","금천(인도네시아). medium"],
"김재원":["Jaewon Kim","https://visualaids.org/artists/jaewon-kim","Visual AIDS(MMCA고양). high"],
"정여름":["Yeoreum Jeong","https://iscp-nyc.org/resident/jeong-yeoreum","ISCP(SeMA벙커2023). high"],
"박성준":["Park Seong Jun","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=1204117","SeMA英(영상). high"],
"최윤":["Choi Yun","https://www.kukjegallery.com/exhibitions/view?seq=281","국제갤러리(SeMA+MMCA). high"],
"안진균":["Jinkyun Ahn","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=1079412","SeMA英. high"],
"김신애":["Shinae Kim","https://sema.seoul.go.kr/en/support/nanji_residency/detail_info?actNo=1090460","SeMA英 난지. high"],
"라이스 브루잉 시스터즈 클럽":["Rice Brewing Sisters Club","https://www.e-flux.com/announcements/6785593/sak-da-the-poetics-of-decomposition","e-flux MMCA(콜렉티브 손혜민·유소윤). high"],
"구수현":["Koo Soohyun","https://sema.seoul.go.kr/en/support/nanji_residency/detail_info?actNo=652998","SeMA英 난지. high"],
"정소영":["Soyoung Chung","http://www.soyoungchung.com/","본인(MMCA+SeMA미디어시티, ≠정서영). high"],
"김채린":["Chaerin Kim","https://www.instagram.com/_chaeerrin/","본인IG. 약-medium"],
"나오미":["NAOMI","https://www.koirhaomi.com/cv","본인(SeMA난지+MMCA고양). high"],
"정승":["Jung Seung","https://monthlyart.com/portfolio-item/","월간미술(설치/미디어). medium"],
"전보경":["Bokyung Jun","http://altspaceloop.com/exhibitions/confirmhumanity-2021","LOOP(SeMA소장4점). high"],
"문은희":["Moon Eunhee","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=1309905","SeMA英 천경자100주년. high"],
"배정례":["Bae Jeong-Rye","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=1309905","SeMA英. high"],
"정성윤":["Sungyoon Jung","https://sungyoonjungpainting.wixsite.com/jung","본인. medium"],
"이영주":["Young Joo Lee","https://youngjoolee.net/news-2/","본인(MMCA2021+SeMA2024). high"],
"최수정":["Choi Soo Jung","https://gallerybaton.com/artists/77-choi-soo-jung/","갤러리바통(MMCA+SeMA). high"],
"이원우":["Wonwoo Lee","https://www.pkmgallery.com/artists/wonwoo-lee/biography","PKM(SeMA). high"],
"구나":["GuNA","https://www.e-flux.com/announcements/657744/looking-after-each-other","e-flux MMCA+SeMA. high"],
"윤가림":["Yoon Kalim","https://yoonkalim.com/CV","본인(SeMA+MMCA). high"],
"추미림":["Chu Mirim","https://k-artist.com/Artist_page.php?tab_num=tab1&artist_num=45","K-Artist(MMCA+SeMA). high"],
"이수진":["Sujin Lee","https://sema.seoul.go.kr/kr/support/emerging_artist/detail_info?actNo=292","SeMA 신진(영문병기, 시각). high"],
"양승원":["Yang Seungwon","https://museumhanmi.or.kr/en/comp-artist/","뮤지엄한미英. high"],
"다이애나랩":["dianalab","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhFlag=2&exhId=202503040001913","MMCA英(콜렉티브). high"],
"제너럴쿤스트":["General Kunst","https://www.generalkunst.com/","콜렉티브 사이트(일반예술). medium"],
"이은경":["Eunkyung Lee","http://eunkyung-lee.com/","본인(런던, 조각). medium"],
"요한한":["Yohan Hàn","https://www.yohanhan.com/curriculum","본인(MMCA YKA2021+SeMA난지). high"],
"엘리 허경란":["Ellie Kyungran Heo","https://elliekyungran.com/cv","본인(MMCA2018+SeMA난지). high"],
"백종관":["Paik Jongkwan","https://www.koreanfilm.or.kr/eng/films/index/peopleView.jsp?peopleCd=20173983","KOFIC英(실험영상). medium"],
"김인숙":["Kim Insook","https://www.lensculture.com/kim-insook","LensCulture(MMCA창동+SeMA). high"],
"황병기":["Hwang Byungki","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=1418254","SeMA英(미디어, ≠가야금명인). high"],
"김기라":["Kira Kim","http://www.east-contemporary.com/2015/10/10/mmca-seoul-korea-artist-prize-2015-kira-kim-na-hyun-inhwan-oh-tae-bum-ha/","MMCA 코리아아티스트프라이즈2015. high"],
"김병주":["Kim Byungjoo","https://www.diacontemporary.com/artist/kim-byungjoo","DIA(MMCA+SeMA소장). high"],
"업체eobchae":["eobchae","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhFlag=2&exhId=202503040001913","MMCA英(콜렉티브). high"],
"송예환":["Song Yehwan","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhFlag=2&exhId=202503040001913","MMCA英 YKA2025. high"],
"김우진":["Kim Woojin","https://www.tokyoartsandspace.jp/en/creator/index/K/1077.html","도쿄아츠앤스페이스(MMCA고양). high"],
"황수현":["Soo-Hyun Hwang","https://ocula.com/artists/soo-hyun-hwang/","Ocula(403, ≠황수연). 약-medium"],
"곽소진":["Kwak Sojin","https://view.asiae.co.kr/en/article/2025053011024052602","아시아경제英. high"],
"감동환":["Donghwan Kam","https://framerframed.nl/en/mensen/donghwan-kam/","Framer Framed(MMCA). high"],
"김태수":["Kim Tae Sue","https://www.kimtaesue.com/","본인. medium"],
"윤지영":["Jiyoung Yoon","https://koreaartistprize.org/project/","코리아아티스트프라이즈(MMCA). high"],
"박민하":["Min Ha Park","https://www.theartnewspaper.com/2025/06/02/min-ha-park-i-think-about-creating-situations-where-things-dont-immediatelyexplain-themselves","Art Newspaper. high"],
"우주+림희영":["Ujoo+Limheeyoung","https://waterfall-artfulliving.com/pages/artist-ujoo-limheeyoung","Waterfall(듀오). high"],
"안성석":["Ahn Sungseok","https://www.e-flux.com/announcements/556073/ahn-sungseok-for-everything-s-tranquility","e-flux MMCA청주2023. high"],
"황수연":["Hwang Sueyon","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=201902150001123","MMCA英 YKA2019(≠황수현). high"],
"제시 천":["Jesse Chun","https://www.jessechun.com/info","본인(MMCA레지+SeMA미디어시티). high"],
"이정우":["Lee Jung-woo","https://www.koreaherald.com/article/10658295","코리아헤럴드(KAP2026). high"],
"신미정":["Shin Mijung","http://geumcheon.blogspot.com/2023/04/shin-mi-jung.html","금천(MMCA고양+SeMA). high"],
"갈라포라스-김":["Gala Porras-Kim","https://spruethmagers.com/artists/gala-porras-kim/","Sprüth Magers(MMCA KAP2023). high"],
};
const existKo=new Set(), existSlug=new Set();
for(const f of readdirSync(DIR).filter(x=>x.endsWith(".yaml"))){ existSlug.add(f.replace(".yaml",""));
  const m=readFileSync(DIR+f,"utf8").match(/full:\s*(.+?)\s*$/m); if(m)existKo.add(m[1].trim()); }
const slugify=s=>s.normalize("NFKD").replace(/[̀-ͯ]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
// ponytail: 2026-08-17 버그수정 — 첫음절=family 슬라이스가 외국이름/콜렉티브를 깨뜨림(reference: project_korean_art_lexicon_miner.md).
// 공백구분 서구식=마지막 토큰이 family, 무공백 5음절+=콜렉티브 추정으로 family/given 생략(strip), 2음절 한국성은 TWO로 우선매치.
const TWO=["남궁","황보","제갈","사공","선우","독고","동방","서문"];
const splitKo=ko=>{
  if(ko.includes(" ")){ const t=ko.split(" "); return {full:ko, given:t.slice(0,-1).join(" "), family:t[t.length-1]}; }
  const two=TWO.find(f=>ko.startsWith(f));
  if(two) return {full:ko, family:two, given:ko.slice(two.length)};
  if(ko.length>=5) return {full:ko}; // 콜렉티브 추정 — family/given 생략
  return {full:ko, family:ko.slice(0,1), given:ko.slice(1)};
};
let made=0,bl=0,dup=0,noslug=0; const recs=[];
for(const [ko,[en,url,note]] of Object.entries(M)){
  if(isBlacklisted(ko)){bl++;continue;}
  if(existKo.has(ko)){dup++;continue;}
  let base=slugify(en); if(!base){noslug++;continue;}
  let slug=base; if(existSlug.has(slug)||recs.some(r=>r.slug===slug)) slug=base+"-"+(slugify(ko)||String(made));
  recs.push({slug, rec:{ id:`person.${slug}`, name:{ko:splitKo(ko), latn:{preferred:en}},
    role:[{aat:"300025103"}], sources:[{url,name_used:en,note:"롱테일 패스3(2기관 웹 검증) — "+note,accessed:"2026-06-22"}], status:"pending_review" }});
  made++;
}
console.log(`생성 ${made} | 블랙 ${bl} | 중복 ${dup} | slug실패 ${noslug}`);
if(APPLY){ for(const {slug,rec} of recs) writeFileSync(DIR+`${slug}.yaml`, yaml.dump(rec,{lineWidth:-1,noRefs:true})); console.log("→ 적용"); }
else console.log("(dry-run)");
