import { writeFileSync, readFileSync, readdirSync } from "node:fs";
import yaml from "js-yaml";
import { isBlacklisted } from "../src/blacklist.js";
const REPO=process.env.HOME+"/Developer/korean-art-lexicon/";
const DIR=REPO+"data/persons/";
const APPLY=process.argv.includes("--apply");
// 롱테일 패스2 (≥3기관 웹 검증). [en, url, note]. 전부 pending_review.
const M={
"박승원":["Seungwon Park","https://planbprojectspace.wordpress.com/2022/09/24/theordinaryday/","Plan B Project Space + KAMS(MMCA/SeMA/NJP/경기 확인). high"],
"권용주":["Yongju Kwon","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=472","SeMA 난지 레지던시 영문. high"],
"전명은":["Eun Chun","https://m.doosanartcenter.com/en/exhibit/artist/317","두산아트센터 영문(geonhi=CHUN Eun). medium"],
"오용석":["Yongseok Oh","https://m.doosanartcenter.com/en/exhibit/artist/205","두산 — MMCA고양2012·SeMA2013 확인. high"],
"언메이크랩":["Unmake Lab","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=202501200001901","MMCA 영문 KAP2025 — 콜렉티브 영문명. high"],
"박보나":["Bona Park","https://www.gallerychosun.com/artists/31-bona-park/","갤러리조선 영문. high"],
"황세준":["Hwang Sejun","https://www.mmcaresearch.kr/timeline/view.do?searchYearmm=199206","MMCA Research Lab(작가 b.1963, ≠연예기획자). high"],
"김기수":["Kim Gisoo","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=201609280000496","MMCA 영문 창동레지던시. high"],
"김태헌":["Kim Tae-hun","https://www.e-flux.com/announcements/42602/a-grain-of-dust-a-drop-of-water","e-flux 광주비엔날레2004(동음 위험, 재확인). medium"],
"이지영":["Jeeyang Lee","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=1314927","SeMA 영문(≠JeeYoung Lee b.1983). high"],
"차미혜":["Mihye Cha","https://chamihye.com/aboutcontact","작가 공식 사이트. high"],
"고정남":["Go Jeongnam","https://ecophotoarchive.org/photographer/33","ECO PHOTO ARCHIVE(MMCA아트뱅크·SeMA·경기). medium"],
"박용석":["Park Yong-seok","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=503089","SeMA 영문 'Collecting for All'. high"],
"최태훈":["Choi Taehoon","https://www.mmca.go.kr/artStudio/artistDetail.do?cinArtId=201603080000143","MMCA 레지던시(≠Choi Tae Hoon b.1965). high"],
"옥정호":["Oak Jungho","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=472","SeMA 영문(성 옥=OAK). high"],
"구성연":["Koo Seongyeon","https://www.galleryjj.org/artists","갤러리JJ. high"],
"홍명섭":["Hong Myung Seop","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=1406567","SeMA 영문(무하이픈). high"],
"배종헌":["Jongheon Bae","https://art-ono.com/gallery-artist/jongheon-bae/","Art Ono Gallery + Glenfiddich. high"],
"조은지":["Eunji Cho","https://m.doosanartcenter.com/en/exhibit/artist/324","두산(≠배우 조은지). high"],
"박선민":["Sunmin Park","https://www.e-flux.com/announcements/516414/on-collecting-time/","e-flux 백남준아트센터. high"],
"한우리":["Uri Han","https://sema.seoul.go.kr/en/support/nanji_residency/detail_info?actNo=1365450","SeMA 난지 영문. high"],
"김준":["Kim Joon","https://sema.seoul.go.kr/kr/whatson/exhibition/detail?exNo=833647","SeMA 난지(≠타투작가 Kim Joon). high"],
"기슬기":["Seulki Ki","https://www.mmca.go.kr/artStudio/artistDetail.do?cinArtId=201402130000038","MMCA 레지던시. high"],
"최원준":["Che Onejoon","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=201802260001023","MMCA 영문 'Civilization'(본인 선택명). high"],
"안은미":["Eunme Ahn","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=391284","SeMA 영문(안무가/퍼포먼스). high"],
"이은우":["Eunu Lee","https://sema.seoul.go.kr/en/whatson/exhibition/detail?artSeq=WORK_0000003858","SeMA 영문 소장. high"],
"김민정":["Kim Min-jung","http://koreanfilm.or.kr/eng/films/index/peopleView.jsp?peopleCd=20278209","비디오/영상작가(≠한지화가 Minjung Kim). medium 동음주의"],
"이채영":["Lee Chae-Young","https://www.lgallerykorea.com/lgalleryartist/chae-young-lee?lang=en","L Gallery(잉크화가, ≠NJP 큐레이터 동명). medium"],
"박계훈":["Park Gye-hoon","https://www.umgallery.co.kr/portfolio-item/park-gye-hoon/","UM Gallery. medium"],
"이웅배":["Ungbai Lee","http://www.massgallery.info/UngbaiLee","MASS Gallery(특이 로마자, 확인요). medium"],
"이중근":["Lee Joong Keun","https://sema.seoul.go.kr/kr/support/nanji_residency/detail_info?actNo=652639","SeMA 난지(≠롯데 회장). high"],
"이창훈":["Lee Changhoon","https://www.mmca.go.kr/artStudio/artistDetail.do?cinArtId=201402130000053","MMCA 레지던시. high"],
"안두진":["Ahn Doojin","https://gallerykiwa.com/artists/53-ahn-doojin/","Gallery Kiwa. high"],
"남경민":["Kyung-Min Nam","https://art.state.gov/personnel/kyung-min_nam/","美 국무부 Art in Embassies(풀/경기 연계 미확인). medium"],
"손종준":["Son Jongjun","https://sonjongjun.com/","작가 공식 + SeMA 난지. high"],
"박고은":["Park Goeun","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=202401150001740","MMCA 영문. high"],
"김진희":["Kim Jinhee","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=202503040001913","MMCA 영문 YKA2025(공통명, 해당작가 특정). high"],
"이주용":["Lee Juyong","https://www.opengallery.co.kr/exhibition/498/","Open Gallery(SeMA 북서울전). medium"],
"박지혜":["Jihye Park","https://jihyeparkartist.com/","작가 공식 + MMCA 아트뱅크(동음 위험). medium"],
"김보경":["Kim Bo Kyung","https://www.artej.kr/kimboktung","ARTE J Gallery(동음 위험). medium"],
"문소현":["Sohyun Moon","https://www.doosanartcenter.com/en/exhibit/artist/394","두산(4기관 다 확인). high"],
"김홍식":["Kim Hong Shik","https://artnedition.com/artist/detail/kim-hongshik/","Art&Edition(MMCA/SeMA/경기 소장 명시). medium"],
"진달래":["Jin Dallae","https://fonderiedarling.org/en/Jin-Dallae","Fonderie Darling(듀오 진달래&박우혁). high"],
"최성록":["Choi Sung Rok","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=503089","SeMA 영문. high"],
"김은형":["Kim Eunhyung","https://www.kimeunhyung.com/","작가 공식. medium"],
"이정민":["Lee Jung Min","https://www.jungmin-artwork.com/","작가 공식 + MMCA 아트뱅크(동음). medium"],
"플라잉시티":["flyingCity","https://www.mmcaresearch.kr/terms/view.do?fid=1186","MMCA Research Lab — 콜렉티브. high"],
"김태균":["Kim Tae Kyun","https://www.artmail.com/db/2021/20210616-kimtaegyun.htm","전시통지(작가 통제). medium"],
"권혁":["Kwon Hyuk","http://www.kwonhyuk.com/about","작가 공식. medium"],
"임옥상":["Lim Ok-sang","https://www.mmca.go.kr/exhibitions/exhibitionsDetail.do?exhId=202210110001577","MMCA 개인전. high"],
"하석준":["Ha Seok-jun","https://www.mmca.go.kr/eng/artStudio/artistDetail.do?cinArtistId=201703130000187","MMCA 고양레지던시. medium"],
"김상균":["Kim Sang Gyun","https://gallerybaton.com/artists/60-kim-sang-gyun/","Gallery Baton(MMCA/SeMA 명시). high"],
"제로랩":["zerolab","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=315321","SeMA 영문 — 콜렉티브(소문자). high"],
"이경희":["Lee Kyung-hee","http://globalprintdouro.com/artists/lee.kyung-hee","Global Print Douro + 대영박물관(동음 多, 판화가). medium"],
"이병찬":["Lee Byungchan","https://www.bclee.org/","작가 공식 + Art Front Gallery. high"],
"호상근":["Ho Sangun","https://sites.google.com/view/hosangun","작가 공식(호상근재현소). medium"],
"김인배":["Kim Inbai","https://www.arariogallery.com/artists/124-kim-inbai/","아라리오갤러리. high"],
"조경재":["Kyoung-Jae Cho","http://geumcheon.blogspot.com/2019/03/kyoung-jae-cho.html","금천예술공장(MMCA) 레지던시. high"],
"김가람":["Ga Ram Kim","https://sema.seoul.go.kr/support/emerging_artist/detail_info?actNo=283","SeMA 신진작가. high"],
"김이박":["Kim Lee-Park","https://www.doosanartcenter.com/en/exhibit/1391","두산(개인 작가, 본명 김현영). high"],
"송주원":["Song Joowon","https://jumpingframes.com/en/film/artist-focus-song-joowon/","안무/영화(미술관 맥락 약). medium"],
"허윤희":["Huh Yun-hee","https://www.youtube.com/watch?v=SigAXO_GNNw","작가 본인 다큐. medium"],
"서민정":["Seo Min Jeong","https://schemaartmuseum.com/2023/03/25/","Schema Art Museum + 경기문화재단. high"],
"김다움":["Daum Kim","https://geumcheon.blogspot.com/2022/02/daum-kim.html","금천예술공장(MMCA) 레지던시. high"],
"장영규":["Young-gyu Jang","https://terosaarinen.com/person/young-gyu-jang/","Tero Saarinen Co(주로 음악/작곡가). medium caveat"],
"민성홍":["SungHong Min","https://gmoma.ggcf.kr/exhibitions/179","경기도미술관 영문. high"],
"니콜라스 펠처":["Nicolas Pelzer","https://www.nicolaspelzer.de/","작가 공식(독일, SeMA/MMCA 레지던시). high"],
"김주리":["Juree Kim","https://www.jureekim.com/","작가 공식. high"],
"캠프":["CAMP","https://www.e-flux.com/announcements/348743/camp-wins-nam-june-paik-art-center-prize-2020","e-flux 백남준AC상2020 — 뭄바이 콜렉티브. high"],
"박관택":["Park Kwantaeck","https://art.snu.ac.kr/en/members/park-kwantaeck/","서울대 미대 교수진. high"],
"김웅용":["WoongYong Kim","https://sema.seoul.go.kr/kr/support/emerging_artist/detail_info?actNo=2510","SeMA 신진작가. high"],
"강호연":["Hoyeon Kang","https://art.snu.ac.kr/en/members/hoyeon-kang/","서울대 미대 + MMCA 영문. high"],
"홍철기":["Hong Chul-Ki","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=345","SeMA 영문 'Is It Noise?'. high"],
"안유리":["Yuri An","https://www.yurian.kr/","작가 공식(SeMA/MMCA/풀 확인). high"],
"한성우":["Han Sungwoo","https://www.e-flux.com/announcements/556991/open-studio-ever-after/","e-flux SeMA 난지. high"],
"김재민이":["Gemini Kim","https://gcc.ggcf.kr/boards/resident-writer/articles/449","경기문화재단 레지던시(본인 transliteration). medium"],
"강상우":["Sangwoo Kang","https://artsandculture.google.com/asset/the-body-alien-sangwoo-kang/UQHjVyogMCRFEA","Google A&C(한국미술관협회). medium"],
"황혜선":["Haesun Hwang","https://www.haesunhwang.com/","작가 공식. high"],
"이슬기":["Lee Seulgi","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=202001140001252","MMCA 영문 KAP2020(국제선 Seulgi Lee). high"],
"심래정":["Sim Raejung","https://www.arariogallery.com/artists/50-sim-raejung/","아라리오갤러리. high"],
"이제":["Leeje","https://m.doosanartcenter.com/en/exhibit/artist/207","두산 — 단어형 자기명. high"],
"임선이":["Im Sunyi","https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=1318668","SeMA 영문. high"],
"구기정":["Gijeong Goo","https://www.e-flux.com/announcements/646227/","e-flux 백남준아트센터. high"],
"이은새":["Eunsae Lee","https://www.gallery2.co.kr/exhibitions/61-as-usual-eunsae-lee/","Gallery2 + 본인사이트. high"],
"안가영":["An Gayoung","https://angayoung.cargo.site/Information","작가 공식 CV(경기 소장). high"],
"황예지":["Yezoi Hwang","https://tinakimgallery.com/exhibitions/63-scoring-the-words-sema-seoul-museum-of-art/","Tina Kim Gallery(SeMA전) — 자기 로마자. high"],
"장한나":["Chang Hanna","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=202503040001913","MMCA 영문 YKA2025(≠첼리스트 Han-Na Chang). high"],
"송민규":["Song Mingyu","https://www.mmca.go.kr/artStudio/artistDetail.do?cinArtId=201802090000209","MMCA 레지던시. high"],
"김보중":["Kim Bojoong","https://www.e-flux.com/announcements/435415/time-of-the-earth/","e-flux MMCA 과천. medium"],
"오주영":["Oh Jooyoung","https://www.mmca.go.kr/artStudio/artistDetail.do?cinArtId=202403140000421","MMCA 고양레지던시. high"],
"정지현":["Jihyun Jung","https://www.doosanartcenter.com/en/exhibit/artist/210","두산(사진가). high"],
"안상수":["Ahn Sang-soo","https://sema.seoul.go.kr/en/knowledge_research/collection/collection_detail?artSeq=WORK_0000004904","SeMA 영문 소장 — 그래픽디자이너/타이포. high"],
"이소요":["Soyo Lee","https://sema.seoul.go.kr/en/support/nanji_residency/detail_info?actNo=652929","SeMA 난지. high"],
"그레이코드":["GRAYCODE","https://graycodejiiiiin.kr/","본인 사이트(듀오 GRAYCODE, jiiiiin 중 조태복). medium"],
"김종학":["Kim Chong Hak","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=201102240000040","MMCA 영문 회고전(b.1937). high"],
"김영글":["Youngle Keem","https://www.sfac.or.kr/artspace/artspace/geumcheon_writerView.do?rsdCode=ART_02_2021&rsdIdx=35","SFAC 금천 + SeMA 난지. high"],
"정희민":["Chung Heemin","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=201902150001123","MMCA 영문 YKA2019. high"],
"신정균":["JungKyun Shin","https://m.doosanartcenter.com/en/exhibit/artist/344","두산. medium"],
"듀킴":["Dew Kim","https://ggallery.kr/artists/dew-kim","G Gallery(씨알콜렉티브 확인). high"],
"조영주":["Youngjoo Cho","https://www.delfinafoundation.com/in-residence/youngjoo-cho/","Delfina Foundation + MMCA. high"],
"권병준":["Byungjun Kwon","http://koreaartistprize.org/en/project/byungjun-kwon/","코리아아티스트프라이즈(MMCA). high"],
"권동현":["Gwon Donghyun","https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhId=202503040001913","MMCA 영문 YKA2025. high"],
"이양희":["Yanghee Lee","https://thepage-gallery.com/exhibitions/51-yanghee-lee-axis-and-foot/","The Page Gallery(≠UN 이양희 b.1956). medium"],
"진시우":["Jin Shiu","https://www.mmca.go.kr/artStudio/artistDetail.do?cinArtId=201701240000163","MMCA 레지던시. high"],
"이문주":["Moonjoo Lee","https://www.mcst.go.kr/kor/s_culture/culture/cultureView.jsp?pSeq=47056","문체부 예술포털 + Bethanien. high"],
"정정주":["Jeong Jeong-ju","https://www.gallerychosun.com/artists/25-jeong-jeong-ju/","갤러리조선. high"],
"류준화":["Ryu Junhwa","https://www.mutualart.com/Artist/Ryu-Junhwa","MMCA 도서목록(Ryu, Jun-Hwa) + 정부아트뱅크. high"],
"김성룡":["Kim Seong Ryong","https://www.bumgallery.com/artists/29-kim-seong-ryong/","BUM Gallery. medium"],
};
const existKo=new Set(), existSlug=new Set();
for(const f of readdirSync(DIR).filter(x=>x.endsWith(".yaml"))){ existSlug.add(f.replace(".yaml",""));
  const m=readFileSync(DIR+f,"utf8").match(/full:\s*([가-힣A-Za-z·\s]+?)\s*$/m); if(m)existKo.add(m[1].trim()); }
const slugify=s=>s.normalize("NFKD").replace(/[̀-ͯ]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const splitKo=ko=>({full:ko, family:ko.slice(0,1), given:ko.slice(1)});
let made=0,bl=0,dup=0; const recs=[];
for(const [ko,[en,url,note]] of Object.entries(M)){
  if(isBlacklisted(ko)){bl++;continue;}
  if(existKo.has(ko)){dup++;continue;}
  let slug=slugify(en); if(existSlug.has(slug)||recs.some(r=>r.slug===slug)) slug=slug+"-"+slugify(ko);
  recs.push({slug, rec:{ id:`person.${slug}`, name:{ko:splitKo(ko), latn:{preferred:en}},
    role:[{aat:"300025103"}], sources:[{url,name_used:en,note:"롱테일 패스2(웹 검증) — "+note,accessed:"2026-06-22"}], status:"pending_review" }});
  made++;
}
console.log(`생성 ${made} | 블랙 ${bl} | 중복 ${dup}`);
if(APPLY){ for(const {slug,rec} of recs) writeFileSync(DIR+`${slug}.yaml`, yaml.dump(rec,{lineWidth:-1,noRefs:true})); console.log("→ 적용"); }
else console.log("(dry-run)");
